### ISSUE TITLE
JSON request body does not represent an object

### ISSUE THREAD

**Issue by KDederichs** [mollie/mollie-api-php#237] opened 2018-07-27 09:27 UTC
## Specifications

  - API Version: 2.0.9

## Describe the issue

Hey,

I'm using your API in combination with Symfony 4 and so far it was working fine.
Out of the blue I started to get 
```Error executing API call (400: Bad Request): The JSON request body does not represent an object..```

Errors while trying to create new customers. 

Any idea what could be causing this?

**Comment by Smitsel** [comment] 2018-07-27 11:13
Can you post a piece of code to give some more context on what you're using?

**Comment by KDederichs** [comment] 2018-07-27 12:10
Sure, 
the scenario is simple:
I have a doctrine listener that queries the Mollie Api after a new customer is registered to get an ID from you. That is done simply by calling:
```php
    /** @var MollieApiClient */
    private $mollie;

    public function __construct(MollieApiClient $mollie)
    {
        $this->mollie = $mollie;
    }

    public function postPersist(LifecycleEventArgs $args)
    {
        /** @var Customer $customer */
        $customer = $args->getEntity();

        if (!$customer instanceof Customer) {
            return;
        }

        $em = $args->getEntityManager();

       $response = $this->mollie->customers->create();

        if ($response) {
            $customer->setMollieId($response->id);
            $em->persist($customer);
            $em->flush();
        }
    }

 ```

The MollieApiClient is registered as a service and is inject by DI into the listener.
The MollieApiClient is simply registered by setting:

```yaml

    GuzzleHttp\Client:
      alias: eight_points_guzzle.client.defaultClient

    Mollie\Api\MollieApiClient:
        calls:
            - method: setApiKey
              arguments:
                  - '%env(MOLLIE_API_KEY)%'
```

**Comment by Smitsel** [comment] 2018-07-27 13:24
Hi @KDederichs,

The error is because you are not supplying any parameters to `$this->mollie->customers->create()`.
Which tries to json_encode the parameters to send to our endpoint. Which will result into an error. Since we're actually trying to json_encode null.

**Comment by Smitsel** [comment] 2018-07-27 13:29
Yes sorry, it is actually a message given by the API.
But the cause is the same, it needs parameters.

I'll check if we can alter this message in the API.

**Comment by KDederichs** [comment] 2018-07-27 13:31
In that case your documentation is wrong though, cause all parameters in create customer are marked optional. So it would make sense that it works with no parameters:
https://docs.mollie.com/reference/v2/customers-api/create-customer

**Comment by willemstuursma** [comment] 2018-07-27 13:38
@smitsel This must be altered by the client. It should not send a body if there are no parameters (empty array).

**Comment by Smitsel** [comment] 2018-07-27 14:04
Thanks for reporting this.
The body should indeed not be passed when left empty.

I've committed and released this under https://github.com/mollie/mollie-api-php/releases/tag/v2.0.10

**Closed** 2018-07-27 14:04 UTC
