### ISSUE TITLE
Giftcard payment details don't include remainderMethod details

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/mollie-api-php#452] opened 2020-03-10 13:15 UTC
When a payment is partially paid with giftcards, the `remainderMethod` specifies the payment method used to pay the remaining amount. However, I can't fetch any additional details about the used method. For example in case of a PayPal transaction, the PayPal reference which is normally accessible through `details.paypalReference`.

The Mollie dashboard does show some of this information (reference, consumer name / email, etc.) so it must be available somewhere. Could this be provided through the API?

Some background info; for accounting purposes we match the paypalReference in Mollie settlements to the same reference supplied by PayPal in an outpayment. This works fine for normal PayPal transactions, but in this particular case it does not because of the missing details.

**Comment by sandervanhooft** [comment] 2020-03-10 13:49
@MollieRick ?

**Comment by willemstuursma** [comment] 2020-03-10 15:53
We could add an include to get the remainderDetails in the same way as from the normal API. 

It would be something like `v2/payments/tr_xxxxx?include=details.remainderDetails`.

**Comment by MollieRick** [comment] 2020-03-12 10:04
Nice one, I'll put it on our backlog.

**Comment by MollieRick** [comment] 2020-03-12 15:56
I added an include to the [Get payment endpoint](https://docs.mollie.com/reference/v2/payments-api/get-payment). You will get the details when you add `details.remainderDetails`as query parameter.

@sandervanhooft Do you need to change something in the client for this?

**Comment by sandervanhooft** [comment] 2020-03-12 17:18
I’ll check tomorrow :)

**Comment by willemstuursma** [comment] 2020-03-12 20:00
@MollieRick It's missing the `remainderDetails` under the gift card specific details.

**Comment by MollieRick** [comment] 2020-03-12 22:06
@willemstuursma In my opinion not necessary since its not there by default. The QR-code is also not there for iDEAL, Bancontact, and Bank transfer.

**Comment by willemstuursma** [comment] 2020-03-13 08:00
Hmm I think it would be an improvement - I'll open an issue with the documentation so we can pick it up later.

**Comment by sandervanhooft** [comment] 2020-03-13 11:06
It seems the client doesn't need modification. I've tested this and it doesn't trow an error:

```php
mollie()->payments->get("tr_UJcqgAjsNc", [
  'include' => 'details.remainderDetails',
]);
```

Note:
1. I don't have a gift card payment available to test against.
2. In the params array, the key must be known, otherwise an error is triggered (i.e. `xinclude`). The value however **does not trigger an error** if inexistent/misspelled (i.e. `details.remainderDetailsXYZ`). Not sure if this is by design?

**Comment by willemstuursma** [comment] 2020-03-13 14:06
@sandervanhooft you can create gift card payments in test mode!

**Comment by sandervanhooft** [comment] 2020-03-13 14:20
@willemstuursma Are you sure? I've enabled a few in the Dashboard, but to no avail.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7265703/76628784-94147300-653d-11ea-9385-caf09b970c52.png">

<img width="814" alt="image" src="https://user-images.githubusercontent.com/7265703/76629165-2a489900-653e-11ea-91d9-729e487b3842.png">

**Comment by MollieRick** [comment] 2020-03-17 13:25
I'll close this issue. The initial issue is solved :)

**Closed by MollieRick** 2020-03-17 13:25 UTC

**Comment by sandervanhooft** [comment] 2020-03-17 13:40
👍 Also, the test-gift-cards-issue is not really high priority (not to me anyway).

**Comment by willemstuursma** [comment] 2020-03-17 14:17
@sandervanhooft maybe you didn't save the page. It works just fine now.

**Comment by SanderVanLeeuwen** [comment] 2020-03-17 16:13
Thanks for the addition. Is it by any chance possible to include those details directly when calling `settlements/*settlementId*/payments`? I'm now performing multiple calls (1. fetch settlement, 2. then settlement payments and then 3. individual payments when the remainderDetails are required) where the third call could be eliminated by including the remainderDetails directly.

I'm already happy with the current changes though, so 'no' is a good enough answer here ;)
