### ISSUE TITLE
Checking for JSON extension

### ISSUE THREAD

**Issue by davdebcom** [mollie/mollie-api-php#355] opened 2019-01-22 14:20 UTC
@JorikMollie and I keep seeing issues with the lack of JSON and the check in the API PHP client. Just tested this and on a server without json, `[satisfiesJsonExtension()](https://github.com/mollie/mollie-api-php/blob/196fc17e05ffd15bd469a6a53ae4700b72a3ec79/src/CompatibilityChecker.php#L53)` still returns true because of the second check for `function_exists('json_encode')`. So, the function `json_encode` can exist while the json PHP extension is not enabled.

In the WooCommerce plugin this can cause fatal errors. I'll add an extra check in the WooCommerce plugin for now, but I think we should change this in the API PHP client. For example:

```
        if (function_exists('extension_loaded') && extension_loaded('json') && function_exists('json_encode')) {
            return true;
        }
```

**Comment by willemstuursma** [comment] 2019-01-22 15:13
@sandervanhooft what's going on here?

**Comment by willemstuursma** [comment] 2019-01-22 15:15
@davdebcom if there is a function called `json_encode()`, the check passes. 

Does this function exist but not work correctly in your setup? Is there some other function needed too, like `json_decode()`?

**Comment by sandervanhooft** [comment] 2019-01-22 16:21
This check was introduced [over 4 years ago](https://github.com/mollie/mollie-api-php/commit/47083b5b0bc26cbfa8ced043a9755c07f8b699b1#diff-45fb8a03798ac24233f4c01472dd530dR114). I'm not convinced yet this should be modified a) in this core client and b) now (breaking change).

> So, the function json_encode can exist while the json PHP extension is not enabled.

It seems to be me this is by design, so you can provide your own encoder.

**Comment by davdebcom** [comment] 2019-01-23 08:21
> It seems to be me this is by design, so you can provide your own encoder.

I'm not sure, the lack of the json PHP extension can cause fatal errors, and the check for that is now not working effectively. But I'll implement my own extra check in the WooCommerce plugin :)

**Comment by willemstuursma** [comment] 2019-01-23 12:44
Unless you make it clear what exactly is missing in the check, we can't really change it @davdebcom.

**Comment by sandervanhooft** [comment] 2019-01-31 07:38
I'm closing this for now, let me know if it should be reopened.

**Closed by sandervanhooft** 2019-01-31 07:38 UTC
