### ISSUE TITLE
Subscription API charges twice on same day

### ISSUE THREAD

**Issue by RaymondBakker** [mollie/mollie-api-php#336] opened 2018-12-16 14:32 UTC
## Specifications

  - API Version: 2.20

## Describe the issue

We're implementing the subscription API but noticed strange behavior that is possibly not intended. These are the steps we're taking:

   - Create customer
   - Create initial payment with ```"sequenceType"	=> \Mollie\Api\Types\SequenceType::SEQUENCETYPE_FIRST```
   - Create subscription in the webhook that gets triggered from the initial payment

An hour after these steps have been taken we see both the initial payment and the first charge of the subscription happening on the same day. Shouldn't the subscription charge start on the date of ```initial payment date + subscription interval``` instead?

If not, what is the best way to prevent this behavior? Setting the `startDate` of the subscription in the future with ```current date + subscription interval```? Or charging $0.01 for the initial payment to trigger SEPA Direct Debit later? The latter doesn't seem to be a good idea because then the checkout page will show $0.01 instead of the actual price of the first term.

**Comment by sandervanhooft** [comment] 2018-12-16 20:02
Hi @RaymondBakker ,

This is by design. The initial mandate payment is totally separated from the subscription.

Both of your suggested solutions are ok. There is a third option if you are dealing with more advanced use cases: after the initial payment, schedule recurring payments triggered from your app.

There is another option, but I'm personally not a big supporter of this: you can create a SEPA directdebit mandate without redirecting the user to Mollie's payment screen.

We are working on a dedicated Laravel Cashier package to handle your use case - if Laravel is your cup of tea :).

I'm closing this issue for now, let me know if you have any follow up question / it needs to be reopened.

**Closed by sandervanhooft** 2018-12-16 20:02 UTC
