### ISSUE TITLE
Duplicated payments might be linked with retry mechanism

### ISSUE THREAD

**Issue by rockandre** [mollie/mollie-api-php#642] opened 2022-10-19 12:50 UTC
## Specifications

  - API Version: 2.0

## Describe the issue

We've noticed some duplicated payments in our Mollie dashboard that might be caused by this: https://github.com/mollie/mollie-api-php/blob/1c92d49f40b6e5c64f92d7f153fb2cf4300c7c17/src/HttpAdapter/CurlMollieHttpAdapter.php#L48

At the same time, we also noticed some HTTP 500 errors on contacting your API.

**Comment by Timollie** [comment] 2022-11-10 09:43
Hi there @rockandre,

sorry for the late response. In this case, the mollie platform did not respond in the expected fashion. A 500 response should not be returned when the payment is created. The mollie-php-api client did its job as expected, retrying the payment. This then led to duplicates.

I think you already spoke to my colleagues at tech support who discussed the issue. Is this correct?

I will close this ticket here, as the client SDK worked as expected. We apologise for the inconvenience caused by the disruption.

**Closed** 2022-11-10 10:40 UTC
